name: Module CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-and-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 安裝依賴（不用 package-lock）
      - run: npm install

      # 驗證 manifest
      - run: npm run validate

      # 重新產生 module_catalog.json
      - run: npm run update-catalog

      # 若屬於 PR，且流程綠燈，自動 merge
      - name: Auto-merge if PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: "squash"
            });
