name: Module CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-and-merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      # ───── 驗證 manifest ─────
      - run: npm run validate

      # ───── 產生最新 catalog ─────
      - run: npm run update-catalog

      # ───── 若有異動就 commit 回 main ─────
      - name: Commit catalog back
        run: |
          git config user.name  "module-bot"
          git config user.email "bot@example.com"

          # git diff --quiet ⇒ 0＝無差異；1＝有差異
          if git diff --quiet module_catalog.json ; then
            echo "No catalog changes."
          else
            git add module_catalog.json
            git commit -m "chore: auto update catalog"
            git push
          fi

      # ───── PR 綠燈時自動合併 ─────
      - name: Auto-merge if PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: "squash"
            });
