name: Module CI

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths:
      - "modules/**/manifest.json"
      - "schema/**"
      - "scripts/**"
      - "package.json"
      - "package-lock.json"

permissions:
  contents: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci || npm i
      - name: Run validator
        run: npm run validate
      - name: Run update catalog
        run: node scripts/update_catalog.cjs || echo "skip catalog"
      - name: Commit catalog back if changed
        run: |
          git config --global user.name  "module-bot"
          git config --global user.email "bot@example.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore(ci): auto update catalog"
            git push
          fi
