name: Module CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "modules/**/manifest.json"
      - "schema/**"
      - "scripts/validate_modules.cjs"
      - "package.json"
  pull_request:
    branches: [ "main" ]
    paths:
      - "modules/**/manifest.json"
      - "schema/**"
      - "scripts/validate_modules.cjs"
      - "package.json"
  workflow_dispatch: {}  # 手動也可

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci || npm i
      - name: Run validator
        run: npm run validate
